# Terragrunt AWS EKS Configuration
# This configuration supports multiple deployment types for load balancers:
# - alb: Application Load Balancer for HTTP/HTTPS traffic (Layer 7)
# - nlb: Network Load Balancer for TCP/UDP traffic (Layer 4)
# - route53: DNS routing (existing)
#
# For Oryx (Enhanced SRS - Simple Realtime Server):
# - ALB handles HTTP-FLV web UI on port 8080
# - NLB handles RTMP push traffic on port 1935
# - Both can be deployed together for complete Oryx functionality

general:
  project: "terragrunt-aws"
  env-short: "dev"
  regions:
    - ap-southeast-1

# No IAM roles for initial deployment - will add access entries manually
default-aws-auth-extra-roles: &default-aws-auth-extra-roles []

# IAM user access entries for cluster access
default-access-entries: &default-access-entries
  - principal-arn: "arn:aws:iam::145065858520:user/dell-admin"
    policy-associations:
      - policy-arn: "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
        access-scope: "cluster"

default-exposed-ports: &default-exposed-ports
  oryx-http-nodeport:
    number: 30080
    protocol: tcp
    cidr-filters:
      - 0.0.0.0/0  # Allow HTTP access from anywhere for ALB
  oryx-rtmp-nodeport:
    number: 31935
    protocol: tcp
    cidr-filters:
      - 0.0.0.0/0  # Allow RTMP access from anywhere for external streaming clients

default-eks-public-access-cidrs: &default-eks-public-access-cidrs
  basti0n: 127.0.0.0/32

default-helm-charts: &default-helm-charts
  oryx:
    repository: oci://ghcr.io/dungxtd/helm
    chart: oryx
    version: 1.0.7
    namespace: oryx
    valuesYAMLTemplate:
      # Oryx configuration - Enhanced SRS with additional features
      candidate: "auto"
      # Use default /data persistence path for Oryx
      persistence:
        enabled: true
        path: "/data"
      conf:
        SRS_LOG_TANK: "console"
        SRS_HTTP_SERVER_ENABLED: "on"
        SRS_HTTP_API_ENABLED: "on"
        SRS_VHOST_HTTP_REMUX_ENABLED: "on"
        SRS_VHOST_HLS_ENABLED: "on"
        SRS_SRT_SERVER_ENABLED: "on"
        SRS_VHOST_SRT_ENABLED: "on"
        SRS_VHOST_SRT_TO_RTMP: "on"
        SRS_RTC_SERVER_ENABLED: "on"
        SRS_RTC_SERVER_CANDIDATE: "*"
        SRS_VHOST_RTC_ENABLED: "on"
        SRS_VHOST_RTC_RTMP_TO_RTC: "on"
        SRS_VHOST_RTC_RTC_TO_RTMP: "on"
        # Enhanced Oryx features
        SRS_VHOST_HTTP_HOOKS_ENABLED: "on"
        SRS_VHOST_DVR_ENABLED: "on"
      # Service configuration - use NodePort to work with ALB/NLB infrastructure
      service:
        type: NodePort     # Use NodePort to work with our ALB/NLB infrastructure
        rtmp: 
          port: 31935      # Service port for RTMP
          nodePort: 31935  # Explicit NodePort for NLB targeting
        http: 
          port: 30080      # Service port for HTTP
          nodePort: 30080  # Explicit NodePort for ALB targeting
        https: 
          port: 30443      # Service port for HTTPS
          nodePort: 30443  # Explicit NodePort
        srt: 
          port: 32080      # Service port for SRT
          nodePort: 32080  # Explicit NodePort
        rtc: 
          port: 32000      # Service port for WebRTC
          nodePort: 32000  # Explicit NodePort

default-eks-addons: &default-eks-addons
  coredns:
    addon-version: v1.12.2-eksbuild.4
    resolve-conflicts: "OVERWRITE"

alb-dns-aliases: &default-alb-dns-aliases
  - api
  - auth-api
  - oryx-web  # For Oryx HTTP-FLV web UI

eks:
  cluster-module-source: cloudposse/eks-cluster/aws
  cluster-module-version: 4.6.0
  node-group-module-source: cloudposse/eks-node-group/aws
  node-group-module-version: 3.3.0
  regions:
    ap-southeast-1:
      cluster-name-0:
        alb-dns-aliases: *default-alb-dns-aliases
        aws-auth-extra-roles: *default-aws-auth-extra-roles
        access-entries: *default-access-entries
        k8s-version: 1.33
        endpoint-public-access: true
        public-access-cidrs:
          all: 0.0.0.0/0
        # Multiple deployment types: ALB for HTTP-FLV (port 8080), NLB for RTMP (port 1935)
        deployment-types:
          - alb   # For Oryx HTTP-FLV web UI on port 8080
          - nlb   # For Oryx RTMP push on port 1935
        # HTTP-only ALB (no SSL certificates, no Route53 required)
        alb-http-only: true

        # Load Balancer specific configurations
        load-balancer-config:
          alb:
            # ALB targets NodePort for HTTP traffic
            target-port: 30080        # NodePort for HTTP service
            target-protocol: "HTTP"
            listener-port: 80         # ALB listens on port 80
            listener-protocol: "HTTP"
            health-check:
              path: "/"
              port: 30080
              protocol: "HTTP"
              matcher: "200-499"
          nlb:
            # NLB targets NodePort for RTMP traffic
            target-port: 31935        # NodePort for RTMP service
            target-protocol: "TCP"
            listener-port: 1935       # NLB listens on port 1935
            listener-protocol: "TCP"
            health-check:
              port: 31935
              protocol: "TCP"
        network:
          vpc: terragrunt-aws
          subnets:
            - name: default
              kind: private
            - name: default
              kind: public  # Need public subnets for load balancers
        addons:
          <<: *default-eks-addons
        helm-charts:
          <<: *default-helm-charts
        # FIXME: missing ec2 names while using managed node groups
        # https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2032
        # potential fix: use our own launch templates
        node-groups:
          workers:
            network:
              subnet:
                name: default
                kind: private
              # Removing availability-zones to use simple private_subnet_ids path
              # availability-zones:
              #   - a
            desired-size: 2
            min-size: 1
            max-size: 10
            ami-type: AL2023_x86_64_STANDARD
            instance-types:
              - t3.small
            autoscaler-enabled: false
            exposed-ports:
              <<: *default-exposed-ports
network:
  default_region: "ap-southeast-1"
  # NOTE: vpc names will be prefixed with env_short
  default_vpc: "terragrunt-aws"
  vpc:
    vpc-module-source: "cloudposse/vpc/aws"
    vpc-module-version: "2.1.1"
    subnet-module-source: "cloudposse/dynamic-subnets/aws"
    subnet-module-version: "2.4.2"
    regions:
      ap-southeast-1:
        terragrunt-aws:
          ipv4-cidr: 172.1.0.0/16
          subnets:
            default:
              ipv4-cidr: 172.1.0.0/18
              private_subnets_enabled: true
              public_subnets_enabled: true
              igw: true
              ngw: true
              availability-zones:
              - ap-southeast-1a
              - ap-southeast-1b
              - ap-southeast-1c
